# Generated by Django 5.1.5 on 2025-02-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Product_Mng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('regular', 'Đá thường'), ('gemstone', 'Đá quý')], default='regular', max_length=10, null=True),
        ),
    ]
