# Generated by Django 5.1.5 on 2025-02-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Product_Mng', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(related_name='product', to='A_Product_Mng.category'),
        ),
    ]
