# Generated by Django 5.1.5 on 2025-02-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Product_Mng', '0009_counter_alter_promotion_options_order_counter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='can_process_payment',
            new_name='can_checkout',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='counter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='A_Product_Mng.counter'),
        ),
    ]
